name: cta_env
channels:
  - conda-forge
dependencies:
  # --- Core Python ---
  - python=3.10

  # --- Data & ML ---
  - pandas
  - numpy
  - scikit-learn

  # --- Notebook & Viz ---
  - jupyterlab
  - matplotlib
  - seaborn

  # --- API & Utils ---
  - requests
  - pip

  - pip:
    - python-dotenv